### ISSUE TITLE
https request not working

### ISSUE THREAD

**Issue by aoe-mak** [bskim45/ccleaner-auto-update#2]
The url for checking and downloading the updates changes.
Checking works when you use the correct one.
Downloading fails due to a hard redirect to https.

Here my config:
`
ccleaner_path:          C:\\Program Files\\CCleaner\\CCleaner.exe
release_url:            http://www.ccleaner.com/ccleaner/download
release_re:             <h3 class="icon_square">Release notes</h3>.+<div class="indent">.+<strong>(.+)</strong> \((.+?)\)
download_url:           http://www.ccleaner.com/ccleaner/download/standard
download_re:            <a href="([^\"]+)">start the download</a>
install_arg:            /S /L=1042
keep_file:              none
`

Here the output:
`
C:\Users\user\Downloads\win-x86-v0.4>CCleanerAutoUpdate.exe
Checking installed CCleaner's version...
Checking current CCleaner version at Piriform...
Installed CCleaner version: 5/41/6446
Current CCleaner version: 5/42/6495 23 Apr 2018
There's a new update available!
Begin download...
Traceback (most recent call last):
  File "CCleanerAutoUpdate.py", line 201, in <module>
  File "CCleanerAutoUpdate.py", line 197, in main
  File "CCleanerAutoUpdate.py", line 116, in check_update
  File "urllib2.pyo", line 154, in urlopen
  File "urllib2.pyo", line 429, in open
  File "urllib2.pyo", line 452, in _open
  File "urllib2.pyo", line 407, in _call_chain
  File "urllib2.pyo", line 1266, in unknown_open
urllib2.URLError: <urlopen error unknown url type: https> 
`

**Comment by bskim45** [comment]
I just released new v0.5.
Please try out and let me know if problem still persists.

**Comment by moerkey** [comment]
Unfortunately not.

`C:\Users\user\Desktop\win-x86-v0.5>CCleanerAutoUpdate.exe
Traceback (most recent call last):
  File "CCleanerAutoUpdate.py", line 9, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "win_unicode_console\__init__.pyo", line 2, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "win_unicode_console\streams.pyo", line 7, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "win_unicode_console\buffer.pyo", line 11, in <module>
  File "ctypes\__init__.pyo", line 379, in __getattr__
  File "ctypes\__init__.pyo", line 384, in __getitem__
AttributeError: function 'PyObject_GetBuffer' not found`

**Comment by moerkey** [comment]
Unfortunately the problem still exists.

> C:\Users\user\Desktop\win-x86-v0.5>CCleanerAutoUpdate.exe
> Traceback (most recent call last):
>   File "CCleanerAutoUpdate.py", line 9, in <module>
>   File "zipextimporter.pyo", line 82, in load_module
>   File "win_unicode_console\__init__.pyo", line 2, in <module>
>   File "zipextimporter.pyo", line 82, in load_module
>   File "win_unicode_console\streams.pyo", line 7, in <module>
>   File "zipextimporter.pyo", line 82, in load_module
>   File "win_unicode_console\buffer.pyo", line 11, in <module>
>   File "ctypes\__init__.pyo", line 379, in __getattr__
>   File "ctypes\__init__.pyo", line 384, in __getitem__
> AttributeError: function 'PyObject_GetBuffer' not found

**Comment by bskim45** [comment]
well it seems that original ssl issue is already solved.
@moerkey please keep in track #5 about buffer issue.

closing.

**Comment by moerkey** [comment]
I switched to https://patchmypc.com/. It is free for private and business usage.
